eadda_app/urls.py
from django.urls import path
from .views import add_stories, index, show_stories, list_songs, add_stories_list, register, user_login, user_logout

app_name = 'eadda_app'

urlpatterns = [
    path('', index, name="index"),
    path('eadda', index, name="index"),
    path('eadda/register/', register, name='register'),
    path('eadda/login/', user_login, name='login'),
    path('eadda/logout/', user_logout, name='logout'),
    path('eadda/lista', list_songs, name="list_songs"),
    path('eadda/add_list', add_stories_list, name="add_stories_list"),
    path('eadda/<slug:song_title_slug>/add/', add_stories, name="add_story"),
    path('eadda/<slug:song_title_slug>/', show_stories, name="show_stories"),

    ]

mundial_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("eadda_app.urls"))
]

eadda_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class SongInfo(models.Model):
    song_title = models.CharField(max_length=222, unique=True)
    song_lyrics = models.TextField(max_length=5000)
    song_video_url = models.URLField(max_length=200, blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.song_title)
        super(SongInfo, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Songs Info'

    def __str__(self):
        return self.song_title


class Stories(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    id_songs = models.ForeignKey(SongInfo, on_delete=models.CASCADE)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Stories'

    def __str__(self):
        return self.author.username

eadda_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Stories


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    username = forms.CharField(label='Nombre de usuario', required=True)
    email = forms.CharField(label='Email', required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class StoryForm(forms.ModelForm):
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Stories
        fields  = ['content', 'views', 'likes']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder':'Escribe aquí!', 'class':"control textarea"}),
        }

eadda_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Stories, SongInfo
from .forms import StoryForm, UserForm
from django.contrib.auth.decorators import login_required


def index(request):
    # show last story
    stories_list = Stories.objects.order_by('-created_at')[0]
    context_dict = {
        'stories': stories_list
    }
    template = 'eadda_app/index.html'
    return render(request, template, context_dict)


def show_stories(request, song_title_slug):
    context_dict = {}
    template = 'eadda_app/stories.html'

    try:
        song = SongInfo.objects.get(slug=song_title_slug)
        stories = Stories.objects.filter(id_songs=song).order_by('-created_at')

        context_dict['stories'] = stories
        context_dict['song'] = song
    except SongInfo.DoesNotExist:
        context_dict['stories'] = None
        context_dict['song'] = None

    return render(request, template, context=context_dict)


def list_songs(request):
    context_dict = {}
    template = 'eadda_app/list_songs.html'
    list_songs = SongInfo.objects.all().order_by('id')
    context_dict['list_songs'] = list_songs

    return render(request, template, context=context_dict)


def add_stories_list(request):
    context_dict = {}
    template = 'eadda_app/add_stories_list.html'
    list_songs = SongInfo.objects.all().order_by('id')
    context_dict['list_songs'] = list_songs

    return render(request, template, context=context_dict)

@login_required
def add_stories(request, song_title_slug):
    try:
        song = SongInfo.objects.get(slug=song_title_slug)
    except SongInfo.DoesNotExist:
        song = None

    if song is None:
        return redirect('/eadda/')

    form = StoryForm()

    if request.method == 'POST':
        form = StoryForm(request.POST)

        if form.is_valid():
            if song:
                story = form.save(commit=False)
                story.author = request.user
                story.id_songs = song
                story.save()

                return redirect(reverse('eadda_app:show_stories', kwargs={'song_title_slug':song.slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'song': song}
    template = 'eadda_app/add_story.html'

    return render(request, template, context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            login(request, user)
            registered = True
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()


    template = 'eadda_app/register.html'
    context_dict = {
        'user_form': user_form,
        'registered': registered
        }

    return render(request, template, context_dict)


def user_login(request):
    template = 'eadda_app/login.html'

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('eadda_app:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Los datos ingresados son incorrectos.")

    return render(request, template)


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('eadda_app:index'))

eadda_app/templates/eadda_app/add_stories_list.html
{% extends 'base.html' %}
{% block content %}

<div class="content">
  <ol type="1">
    {% for song in list_songs %}
    <a href="{% url 'eadda_app:add_story' song.slug %}">
      <li>  {{ song.song_title}}</li>
    </a>
    {% endfor %}
  </ol>
</div>



{% endblock %}

eadda_app/templates/eadda_app/add_story.html
{% extends 'base.html' %}
{% block content %}

<h1 class="subtitle">
  {{ song.song_title }}
</h1>

<form class="box" role="form" action="/eadda/{{song.slug}}/add/" method="post">
  {% csrf_token %}
  <div class="content">
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
    {% endfor %}

  </div>
  <button type="submit" value="Guardar" class="button is-primary is-rounded">Guardar!</button>
</form>
<div class="">

</div>
<div class="block">
  <a href="{{ song.song_video_url }}"  target="_blank" >
    <button class="button">
      <span class="icon">
        <i class="fa-brands fa-youtube"></i>
      </span>
      <span>Escuchar canción en youtube</span>
    </button>
  </a>
</div>
<div class="content">

  {{ song.song_lyrics|linebreaks }}

</div>
{% endblock %}

eadda_app/templates/eadda_app/index.html
{% extends 'base.html' %}
{% block content %}
<div>
  <section class="hero is-small is-primary">
    <div class="hero-body">
      <p class="title">
        EADDA
      </p>
      <p class="subtitle">
      Escribí un texto utilizando las canciones del
      <strong>"Amor después del amor"</strong> como disparador.
      </p>
      {% if user.is_authenticated %}
      <a href="{% url 'eadda_app:add_stories_list' %}">
        Hola, {{ user.username }}!
        Selecciona una canción de la <strong>lista</strong> para comenzar a escribir!
        <br>
        Ver lista de canciones
      </a>
      {% else %}
      <p class="block">
        <a href="{% url 'eadda_app:login' %}">
          Ingresa para comenzar!
        </a>
      </p>
      {% endif %}
    </div>
  </section>
  {% if stories %}
  <section class="section">
    <p class="is-size-6 title">
      Últimos textos agregados:
    </p>
  <div class="box mb-4">
    <h3 class="is-size-6 subtitle">
      <a href="/eadda/{{ stories.id_songs.slug}}">
        {{ stories.id_songs.song_title}}
      </a>
    </h3>
      {{ stories.content|linebreaksbr }}
      <p class="mt-4">
        <small>Escrito por: {{ stories.author.username }}</small>
      </p>
  </div>

  </section>
  {% else %}
  <strong>Nada por ahora! </strong>
  {% endif %}
</div>
{% endblock %}

eadda_app/templates/eadda_app/list_songs.html
{% extends 'base.html' %}
{% block content %}

<div class="content">
  <ol type="1">
    {% for song in list_songs %}
    <a href="{% url 'eadda_app:show_stories' song.slug %}">
      <li>  {{ song.song_title}}</li>
    </a>
    {% endfor %}
  </ol>
</div>



{% endblock %}

eadda_app/templates/eadda_app/login.html
{% extends 'base.html' %}

{% block title_block %}Login {% endblock %}
{% block content %}
<h1>Ingresa para poder escribir.</h1>
  <form class="box" role="form" id="login_form" method="post" action="{% url 'eadda_app:login' %}">
      {% csrf_token %}
      <div class="field">
        <div class="control">
          <input class="input" type="text" placeholder="Usuario" name="username" id="id_username" required>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <input class="input" type="password" name="password" placeholder="Contraseña" id="id_password">
        </div>
      </div>
      <input class="button is-light" type="submit" value="Entrar!">
  </form>
  <h1>
    <a href="{% url 'eadda_app:register' %}">
      Registrate acá!
    </a>
  </h1>
{% endblock %}

eadda_app/templates/eadda_app/register.html
{% extends 'base.html' %}

{% block title_block %}Sign Up {% endblock %}
{% block content %}
{% if registered %}
<strong> ¡Ya estás registrado! </strong>
<a href="{% url 'eadda_app:add_stories_list' %}">Escribir una historia.</a>
{% else %}
<div class="block">
  <h1>Completa los campos a continuación:</h1>
</div>

<form class="box" role="form" id="user_form" method="post" action=".">
{% csrf_token %}
  <div class="field">
    <label for="id_username" class="label">Nombre de usuario:</label>
    <div class="control">
      <input class="input" type="text" placeholder="Usuario" name="username" id="id_username">
    </div>
  </div>

  <!-- <div class="field">
    <label for="id_email" class="label">Email</label>
    <div class="control">
      <input class="input" type="email" placeholder="Email" name="email" id="id_email">
    </div>
  </div> -->

  <div class="field">
    <label for="id_password" class="label">Password</label>
    <div class="control">
      <input class="input" type="password" name="password" placeholder="Password" id="id_password">
    </div>
  </div>

  <button type="submit" name="submit" value="Registrarse" class="button is-primary">Sign in</button>
</form>

{% endif %}
{% endblock %}

eadda_app/templates/eadda_app/stories.html
{% extends 'base.html' %}
{% block title_block %} {{ song.song_title }} {% endblock %}
{% block content %}

{% if song %}
  <h1 class="title" >{{ song.song_title }}</h1>
  {% if stories %}
    {% for story in stories  %}
    <div class="box mb-4">
        {{ story.content|linebreaksbr }}
        <p class="mt-4">
          <small>Escrito por: {{ story.author.username }}</small>
        </p>
    </div>

    <!-- <section>
        <h1 class="subtitle">{{ story.author.username }} escribió:</h1>
        <p class="mb-4">
          {{ story.content }}
        </p>
      </section> -->
    {% endfor %}
  {% else %}
  <strong>No hay historias para esta canción</strong>
  {% endif %}
{% else %}
  No encontrado
{% endif %}


{% endblock %}

mundial_project/templates/base.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>EADDA | {% block title_block %}{% endblock %}</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
      <script src="https://kit.fontawesome.com/292b475904.js" crossorigin="anonymous"></script>
   </head>
   <body>
     <nav class="navbar container" role="navigation" aria-label="main navigation">
       <div class="navbar-brand">
         <a class="navbar-item" href="{% url 'eadda_app:index' %}">
           Inicio
         </a>
         <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
           <span aria-hidden="true"></span>
           <span aria-hidden="true"></span>
           <span aria-hidden="true"></span>
         </a>
       </div>

       <div id="navbarBasicExample" class="navbar-menu" id="navMenu" >
         <div class="navbar-start">
           <a class="navbar-item"  href="{% url 'eadda_app:list_songs' %}">
            Textos por canción
           </a>
           {% if user.is_authenticated %}
           <a class="navbar-item" href="{% url 'eadda_app:add_stories_list' %}">
             Escribir un texto
           </a>
           {% endif %}
         </div>

         <div class="navbar-end">
           <div class="navbar-item">
             {% if user.is_authenticated %}
             <!-- <a class="navbar-item">
               Hola, {{ user.username }}!
             </a> -->
             <a class="button is-light" href="{% url 'eadda_app:logout' %}">
               Salir
             </a>
             {% else %}
             <div class="buttons">
               <a class="button is-primary" href="{% url 'eadda_app:register' %}">
                 <strong>Registrarse</strong>
               </a>
               <a class="button is-light" href="{% url 'eadda_app:login' %}">
                 Ingresar
               </a>
             </div>
             {% endif %}
           </div>
         </div>
       </div>
     </nav>
      <section class="section">
         <div class="container">
           <div class="columns is-centered">
             <div class="column is-half">
               {% block content %}
               {% endblock %}
             </div>
           </div>
         </div>
      </section>

      <footer class="footer">
        <div class="content has-text-centered">
          <p> EADDA 2022</p>
        </div>
      </footer>

      <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });

      });
      </script>

   </body>

</html>